stages:
  - test
  - build

Test:
  stage: test
  tags:
    - python
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  before_script:
    - export PYTHONPATH=`pwd`
    - pip install -r requirements.txt
  script:
    - pytest --cov=myprj --cov-report=xml --junitxml=junit.xml
  coverage: '/coverage: \d+.\d+% of statements/'
#  coverage: '/^TOTAL.*\s(\d+\%)$/'

Job_1:
  stage: build
  tags:
    - python
  artifacts:
    paths:
      - logs.txt
  script:
    - echo START BUILD!!!
    - ls -la
    - hostname
    - pwd
    - python myprj/main.py
