stages:
  - test
  - build

Test:
  stage: test
  tags:
    - python
  artifacts:
    reports:
      junit: junit.xml
      cyclonedx: cyclonedx.json
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  before_script:
    - export PYTHONPATH=`pwd`
    - pip install -r requirements.txt
  script:
    - pytest --cov --cov-report term-missing --cov-report xml:./coverage.xml --junitxml=./junit.xml
    - python -m cyclonedx_py -r --format json
  coverage: '/TOTAL.*\s+(\d+%)$/'

Job_1:
  stage: build
  tags:
    - python
  artifacts:
    paths:
      - logs.txt
  script:
    - echo START BUILD!!!
    - ls -la
    - hostname
    - pwd
    - python myprj/main.py

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
#  - template: Auto-DevOps.gitlab-ci.yml
#sast:
#  stage: test