version: '3.8'

services:
  servver_app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '5000:5000'
    command: [
      "poetry", "run","uvicorn", "server:app",
      "--port", "5000",
      "--host", "0.0.0.0"
    ]

  python-app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - CHECK_STR=${CHECK_STR}
    volumes:
      - $PWD/result:/app/result
    command: [ "poetry", "run", "python", "main.py" ]

networks:
  default:
    driver: bridge
